# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='New-Model-S-Tesla-9.jpg', null=True, upload_to=b''),
        ),
    ]
