# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0005_auto_20180107_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
