# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0006_auto_20180107_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DearDiary.Post')),
            ],
        ),
    ]
