# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0007_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='Post',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DearDiary.Post'),
        ),
    ]
