# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0009_auto_20180224_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
