# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0010_auto_20180224_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to=b'')),
            ],
        ),
    ]
