# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='DearDiary.Post_image'),
            preserve_default=False,
        ),
    ]
