# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DearDiary', '0012_auto_20180421_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_image',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(db_column='image', on_delete=django.db.models.deletion.CASCADE, to='DearDiary.Post_image'),
        ),
    ]
