# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0012_auto_20180415_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DearDiary.Post_image'),
        ),
    ]
