# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0013_auto_20180421_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_image',
            name='created_by_user',
        ),
        migrations.AlterField(
            model_name='post_image',
            name='image',
            field=models.FileField(blank=True, db_column='image', default=None, null=True, upload_to=b''),
        ),
    ]
