# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0014_auto_20180415_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='id',
            field=models.IntegerField(db_column=id, primary_key=True, serialize=False),
        ),
    ]
