# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0015_post_image_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='DearDiary.Post_image'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
