# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0018_remove_post_image_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DearDiary.Post_image'),
        ),
    ]
