# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0021_auto_20180427_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DearDiary.Post'),
        ),
    ]
