# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DearDiary', '0022_auto_20180427_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
